spring:
  datasource:
    url: jdbc:h2:mem:creator_settlement # 메모리 DB
    driver-class-name: org.h2.Driver
    username: user
    password: pwd

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  seed:
    enabled: true